apiVersion: v1
kind: Service
metadata:
  name: payment-gateway
  namespace: default
  labels:
    app: payment-gateway
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30501
  selector:
    app: payment-gateway
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: payment-gateway-stable
  namespace: default
  labels:
    app: payment-gateway
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: payment-gateway

---
apiVersion: v1
kind: Service
metadata:
  name: payment-gateway-canary
  namespace: default
  labels:
    app: payment-gateway
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: payment-gateway
