apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-gateway-monitor
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: payment-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
      scrapeTimeout: 4s
